<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-android</TargetFramework>
    <SupportedOSPlatformVersion>24</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
    <ApplicationId>cn.classisland.management</ApplicationId>
    <ApplicationTitle>ClassIsland 集控</ApplicationTitle>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>0.1.0</ApplicationDisplayVersion>
    <AndroidPackageFormat>apk</AndroidPackageFormat>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Client/ClassIsland.Management.Client.csproj" />
    <PackageReference Include="Avalonia.Android" Version="$(AvaloniaVersion)" />
  </ItemGroup>
</Project>
